---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebconfigurable-demo
  labels:
    app: samplewebconfigurable-demo
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: samplewebconfigurable-demo
  template:
    metadata:
      labels:
        app: samplewebconfigurable-demo
    spec:
      containers:
      - name: samplewebconfigurable-demo
        image: acrcsea2np1hello.azurecr.io/samplewebbasic:70
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: MySetting
          value: "DEPLOYMENT_YAML_MY_SETTING"
        - name: TestSetting
          value: "hello from Kubernetes"
        - name: TestGetUri
          value: "http://samplebackend:8081/api/values"
---
apiVersion: v1
kind: Service
metadata:
  name: samplewebconfigurable-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: samplewebconfigurable-demo
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: samplewebconfigurable-demo-hpa
  labels:
    app: samplewebconfigurable-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: samplewebconfigurable-demo
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 20 
